### ISSUE TITLE
Category feeds have an incorrect feed_url

### ISSUE THREAD

**Issue by oddevan** [manton/jsonfeed-wp#12]
A JSON feed generated for a category has the correct posts but an incorrect feed_url; it shows the home page feed instead.

**Comment by oddevan** [comment]
For example, the [oddEvan Featured category JSON feed](http://beta.oddevan.com/category/featured/feed/json/) has `http://beta.oddevan.com/feed/json/` as its `feed_url`. To contrast, the [oddEvan Featured category Atom feed](http://beta.oddevan.com/category/featured/feed/atom/) has `http://beta.oddevan.com/category/featured/feed/atom/` as its `link rel="self"`.

I'm not sure at the moment how to fix it; I'll take a dive in later unless someone else is already working on this.

**Comment by manton** [comment]
Thanks, we missed this. I checked the default Atom feed and it calls `self_link()`, which we can't use directly here but can essentially copy if there's not a better solution.

**Comment by manton** [comment]
Oh sorry, just noticed you've already done this in a pull request. I'll close this and we can track it there.
