### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by davidfindlay** [manton/jsonfeed-wp#14]
One thing I see lacking in RSS is the ability to have items that advise about future events. For instance, I want to syndicate the Swimming Meet Event calendar for my sporting organisation, so that individual clubs could include the calendar of upcoming events on their site. 

With RSS I could do so by putting the upcoming date in the title of the item. However I'd like to be more semantic about it. 

I'd suggest just adding a 'eventdate' optional field to item. This would then allow implementations to feature future events.

**Comment by manton** [comment]
Thanks for the feedback. However, you should file this over in the main JSON Feed repository. Most of the feature requests are being discussed over there if they aren't specific to WordPress.

https://github.com/brentsimmons/JSONFeed/issues

**Comment by davidfindlay** [comment]
Thanks, I've done so.
