### ISSUE TITLE
It miss the enclosure

### ISSUE THREAD

**Issue by onigetoc** [manton/jsonfeed-wp#17]
Like every RSS to json scripts it always miss the enclosure.
Audios, Videos, Images

**Comment by nikornnanta** [comment]
On issur

**Comment by dshanske** [comment]
@onigetoc Could you elaborate?

**Comment by onigetoc** [comment]
https://www.w3schools.com/xml/rss_tag_enclosure.asp

**Comment by dshanske** [comment]
@onigetoc I understand what an enclosure is, but I don't understand what you are asking to have done. Jsonfeed calls enclosures attachments and it should add them automatically.

**Comment by onigetoc** [comment]
Not all enclosures work, it's why i did post this message, if it worked i
would not.
this was a old issue i posted many month ago. i still prefer my php
podparser :)
https://github.com/onigetoc/Podcast-parser-for-jPlayer/blob/master/assets/podparser.php

Le mer. 21 nov. 2018 à 07:42, David Shanske <notifications@github.com> a
écrit :

**Comment by dshanske** [comment]
Changes to attachment code. Beyond this, there is a filter in do_enclose.
