### ISSUE TITLE
[Request] Ability to Set Feed Content to Post Content or Excerpt

### ISSUE THREAD

**Issue by buffaloseven** [manton/jsonfeed-wp#18]
I've been manually modifying `feed-template.php` each update, but it would be nice to see a UI for alternating the content between the post content or the excerpt.

**Comment by dshanske** [comment]
@buffaloseven Would you be happy if I made it so it would honor the RSS feed setting for this?

**Comment by buffaloseven** [comment]
@dshanske Yep. I think that's probably how it *should* be done to minimize any confusion or inconsistency in behaviour.
