### ISSUE TITLE
Flushing rewrites on init

### ISSUE THREAD

**Issue by norcross** [manton/jsonfeed-wp#2]
Should look at using `register_activation_hook` instead because it only needs to be run once. Happy to write the PR if you'd like.

**Comment by tollmanz** [comment]
Just to amplify this a bit, `init` runs on every single request, which causes the rewrites to be flushed, which is an expensive operation and causes DB writes.

**Comment by danielpunkass** [comment]
Sounds like something @manton and I are probably just not up to speed with. I think I speak for him too when I say we would welcome any pull requests that bring the extension up to better standards for functionality or performance! Thanks for the issue.

**Comment by norcross** [comment]
@tollmanz you wanna take a pass at it, or should I? (I've got free time this evening)

**Comment by tollmanz** [comment]
It's all you @norcross!

**Comment by kasparsd** [comment]
Found this thread only after I had created the patch #4.

**Comment by norcross** [comment]
@kasparsd  that's what I get for falling asleep early 😂
