### ISSUE TITLE
Number of posts

### ISSUE THREAD

**Issue by muoto** [manton/jsonfeed-wp#22]
How would one go about increasing the number of posts displayed?

**Comment by brinkdinges** [comment]
I had the same question yesterday. Turns out there is a Wordpress settings for the amount of posts in the RSS feed and it also works on this feed.

https://www.wpbeginner.com/wp-tutorials/how-to-limit-the-number-of-posts-displayed-in-rss-feed/

**Comment by manton** [comment]
Thanks @brinkdinges! Yep, changing that setting should work for JSON Feed as well.

**Comment by dshanske** [comment]
Probably should add to the readme
