### ISSUE TITLE
Requires at least WP 4.4, not WP 4.0 as specified

### ISSUE THREAD

**Issue by sardisson** [manton/jsonfeed-wp#31]
The `Readme.txt` and other info files still claim the plugin requires only WP 4.0 or higher, but it currently (since the August 2018 flurry of commits) using functions in `feed-template.php` that were introduced in WP 4.4, e.g. `wp_parse_url()` and `get_the_post_thumbnail_url()`, causing the feed to return HTTP 500.

There may be other function usages from even newer WP versions, but I stopped checking after those two.

**Comment by dshanske** [comment]
I will address it. I did the August commits

**Comment by dshanske** [comment]
Thinking the easiest solution is to bump the requirements to 4.9. WordPress practice for many projects is to support 2 major versions back. But Gutenberg went in in 5.0 so many stayed on the 4.9 code, including ClassicPress.
