### ISSUE TITLE
remove feed-template.php from wordpress.org release

### ISSUE THREAD

**Issue by alpipego** [manton/jsonfeed-wp#41]
The file `feed-template.php` is not part of this repository but it's in the version on wordpress.org.

**Comment by alpipego** [comment]
Oooh I get it, it's NOT supposed to be there!!

**Comment by alpipego** [comment]
I have updated the title to reflect this, instead of adding the file to GitHub it should be removed from the release on wordpress.org.

**Comment by dshanske** [comment]
It's part of the deployment script I've been using. Recently, I have switched in other projects to GitHub Actions, will do that here. It works a lot more reliably for SVN deployment and will manually remove the file
