### ISSUE TITLE
Properly add tags to github

### ISSUE THREAD

**Issue by alpipego** [manton/jsonfeed-wp#43]
I noticed the plugin is up to version 1.3.0 on wordpress.org but only versions 1.0, 1.1.1, and 1.1.2 exist on GitHub. Is it possible to add the missing tags (or at least future ones) to GitHub as well?

**Comment by dshanske** [comment]
Will be doing this as part of the deployment process shift.

**Comment by dshanske** [comment]
This was addressed going forward
