### ISSUE TITLE
application/feed+json instead of application/json

### ISSUE THREAD

**Issue by Morid1n** [manton/jsonfeed-wp#50]
Hey.

I'm having an issue with my JSON feeds in Feedly — they're not showing up at all in their listings. I emailed them and they wrote back that they're expecting an `application/json` in the header, while getting an `application/feed+json` instead.

I don't know who is at fault here but I'd love to be able to solve this issue.

**Comment by manton** [comment]
We are moving to `application/feed+json` in JSON Feed version 1.1, and the WordPress plugin has already been updated to use that type. Best thing would be for Feedly to support both.

**Comment by Morid1n** [comment]
I got a reply from Feedly:

> We can try to push an update this week. If you are in contact with the json feed team, it would be great if you could communicate that a providing a heads up to major feed-reader apps would be great for changes like this.

**Comment by manton** [comment]
Thanks. They're right, we should try to reach out to some of the major feed readers. The rollout of version 1.1 has been a little unusual since the WordPress plugin changes shipped before the spec was officially updated.

**Comment by dshanske** [comment]
That's my fault...sorry

**Comment by manton** [comment]
No worries. The 1.1 process has been slow, and that's on me.

**Comment by Morid1n** [comment]
I manually edited the WP plugin in the meantime and changed it back to `application/json`, so my RSS feeds work properly, and I'll update this thread once Feedly Pro confirms that they have adopted the new spec, at which point I'll revert the changes I made to the plugin.

Thanks for everything guys!

**Comment by gr36** [comment]
I am getting the same error when trying to validate on https://validator.jsonfeed.org/

as well as nothing appearing on micro.blog

**Comment by manton** [comment]
The JSON Feed validator has been updated with better support for version 1.1.
