### ISSUE TITLE
Should we minify this json result?

### ISSUE THREAD

**Issue by mrnonz** [manton/jsonfeed-wp#52]
After I test with my website, I try to minify it's can reduce size around -50%. So It's can increase performance for us.

Thank you,

**Comment by manton** [comment]
For my other feeds (like in Micro.blog) I tend to decide this based on whether I think someone might ever load it in their browser, where being human-readable is convenient. I don't have a good sense of whether it's common to minify in WordPress for other types of requests, but maybe @dshanske does.

**Comment by dshanske** [comment]
WordPress does not minify the returns from its REST API.
