### ISSUE TITLE
Hide private posts

### ISSUE THREAD

**Issue by tdittmar** [manton/jsonfeed-wp#56]
I can't seem to find a way to filter posts by status in the URL (like /feed/json?post_status=publish). 
Currently, the feed for one post type also returns private items, which I want to exclude from the feed. How would I achieve that?

**Comment by manton** [comment]
Good catch, thanks. I'm not sure where to hook into this but maybe @dshanske has an idea.

**Comment by dshanske** [comment]
Did you try looking when not logged in? I'll investigate this either way.

**Comment by tdittmar** [comment]
Actually I haven't tried when not logged in. While that might be the cause, I still thank you for investigating.
