### ISSUE TITLE
JSON feed isn't cached.

### ISSUE THREAD

**Issue by chockenberry** [manton/jsonfeed-wp#67]
It appears that the JSON response for the feed isn't cached. I noticed this while tweaking on some things in my functions.php code (to remove Emoji images from the feeds).

The JSON feed updated immediately, but the RSS feed needed the cache to be deleted.

I poked around the `wp-content/cache/supercache/<SITE>/feed` directory and the only thing in there are XML feeds.

As adoption of JSON Feed picks up, this could become a performance issue for sites.

**Comment by danielpunkass** [comment]
I suspect we'll have to arrange for every popular caching plugin to treat our JSON feed files as cacheable. I use W3 Total Cache and examining their source base I see the decision whether to cache or not is controlled by a built-in list of types, but they also support a plugin hook `w3tc_is_cacheable_content_type` which we could add to the plugin, and return true for `application/feed+json`. I'm not sure if there's a higher level way to indicate that a given file should be cached by whatever caching plugin happens to be in use.

**Comment by danielpunkass** [comment]
For WP-SuperCache it looks like the file is not cached because it doesn't have a "closing tag". There is a `wp_cache_eof_tags` hook that we could override that might get us to have it treat the JSON feed file as cacheable.

**Comment by dshanske** [comment]
1.4.5 adds in the W3TC Filter. Best I can do per notes.
