### ISSUE TITLE
wordpress.org/plugin/search/jsonfeed/ returns 0 

### ISSUE THREAD

**Issue by xuv** [manton/jsonfeed-wp#9]
Hello

This is great. Thanks for this. Would love to use it on the blogs I am in charge of. Though, even if it's just dropping a folder in my plugins folder, I think it would be easier and would reach mass adoption more quickly if you could add it to https://wordpress.org/plugins/ 

Thanks again for your work.

**Comment by manton** [comment]
Thanks! We've submitted it to the WordPress directory and it was approved, but there's something holding it up from going live. Hope to have it resolved soon.

**Comment by xuv** [comment]
Glad to hear this. And thanks for the explanation. Crossing fingers Wordpress validates this asap.

**Comment by manton** [comment]
The plugin is now in the directory! A search for "jsonfeed" will find it.

**Comment by renatonascalves** [comment]
Good! :)
